=== darrenwshort/cisw440-final-project/final-project-concert-series.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="ConcertSeries">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Event" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="EventName" type="xs:string"/>
              <xs:element name="EventDate">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Month" type="xs:string"/>
                    <xs:element name="Day" type="xs:positiveInteger"/>
                    <xs:element name="Year" type="xs:positiveInteger"/>
                    <xs:element name="StartTime" type="xs:string"/>
                    <xs:element name="EndTime" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="TicketPrice" type="xs:string"/>
              <xs:element name="Venue" type="xs:string"/>
              <xs:element name="BandName" type="xs:string"/>
              <xs:element name="BandNoOfMembers" type="xs:positiveInteger"/>
              <xs:element name="BandOrigin" type="xs:string"/>
              <xs:element name="BandGenre" type="xs:string"/>
              <xs:element name="BandYearsActive" type="xs:positiveInteger"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:positiveInteger"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== darrenwshort/cisw440-final-project/final-project-concert-series.xml.test.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="final-project-concert-series.xsl" ?> 

<!-- ========================================== -->
<!-- Final Project:  Concert Series						 -->
<!-- Course:         CISW 440 Spr 2020          -->
<!-- Author:         Darren Short               -->
<!-- SID:            w1765868                   -->
<!-- ========================================== -->

<!-- Concert Series 2020 -->
<ConcertSeries xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="final-project-concert-series.xsd">
  <Event id="1">
    <EventName>Eddie Takes Vacaville!</EventName>
    <EventDate>
      <Month>June</Month>
      <Day>4</Day>
      <Year>2020</Year>
      <StartTime>20:00</StartTime>
      <EndTime>23:30</EndTime>
    </EventDate>
    <TicketPrice>99.00</TicketPrice>
    <Venue>Roger's Rock N Roll Shack</Venue>
    <BandName>Iron Maiden</BandName>
    <BandNoOfMembers>6</BandNoOfMembers>
    <BandOrigin>England</BandOrigin>
    <BandGenre>Metal</BandGenre>
    <BandYearsActive>40</BandYearsActive>
  </Event>
  <Event id="2">
    <EventName>The Creek's Summer Series with The Eagles</EventName>
    <EventDate>
      <Month>June</Month>
      <Day>11</Day>
      <Year>2020</Year>
      <StartTime>19:30</StartTime>
      <EndTime>23:30</EndTime>
    </EventDate>
    <TicketPrice>225.00</TicketPrice>
    <Venue>The Agenda</Venue>
    <BandName>The Eagles</BandName>
    <BandNoOfMembers>7</BandNoOfMembers>
    <BandOrigin>United States</BandOrigin>
    <BandGenre>Rock</BandGenre>
    <BandYearsActive>43</BandYearsActive>
  </Event>
</ConcertSeries>
